### ISSUE TITLE
native 如何传参给 weex

### ISSUE THREAD

**Issue by lixingdecai** [iChenLei/weex-android-joke#1]
我看到你在`CommentActivity`里 里面有一局代码`String json = "{'a':2,'b':'chen'}";` 应该是用在
 `mInstance.render("WeexQuickStart",WXFileUtils.loadAsset("weex/modules/comment.js",this), json, null, -1, -1, WXRenderStrategy.APPEND_ASYNC);}`
这个方法传到comment.js中，可是在comment.js中要如何调用传进来的参数，代码中没有找到

**Comment by iChenLei** [comment]
这个貌似得写扩展，weex和weex页面之间传递数据可以使用weex自带得storage，native我用的sp,在weex页面ready阶段拿到值，都是hack的写法，不推荐。现在我也不怎么用weex了，不好给建议。。
